export const USER_START = "USER_START";
export const USER_FAIL = "USER_FAIL";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_CUR_USER_SUCCESS = "CHECK_AUTH_SUCCESS";

export const JOB_START = "JOB_START";
export const JOB_FAIL = "JOB_FAIL";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS";
export const GET_STATS_SUCCESS = "GET_STATS_SUCCESS";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
